// Copyright (c) 2026 Beijing Volcano Engine Technology Ltd.
// SPDX-License-Identifier: MIT

package openapi

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

type staticProvider struct {
	credential Credential
	err        error
}

func (p staticProvider) Credentials(context.Context) (Credential, error) {
	return p.credential, p.err
}

func testClient(server *httptest.Server) AgentClient {
	client := NewClient(staticProvider{credential: Credential{
		AccessKeyID:     "ak",
		SecretAccessKey: "sk",
		SessionToken:    "session",
	}})
	client.Endpoint = server.URL
	client.HTTP = server.Client()
	return NewAgentClient(client)
}

func sampleStartReq() StartVoiceChatRequest {
	return StartVoiceChatRequest{
		AppID: "app", BusinessID: "vertc_cli", RoomID: "room", TaskID: "task",
		// Config is passed through verbatim (as generated by the console).
		Config:      json.RawMessage(`{"ASRConfig":{"Provider":"volcano"},"LLMConfig":{"Mode":"ArkV3","EndPointId":"ep-test"}}`),
		AgentConfig: map[string]any{"UserId": "agent-01", "TargetUserId": []string{"user-01"}, "WelcomeMessage": "hi"},
	}
}

func TestRequestMarshalsVolcFieldNames(t *testing.T) {
	b, _ := json.Marshal(sampleStartReq())
	s := string(b)
	for _, want := range []string{`"AppId"`, `"BusinessId":"vertc_cli"`, `"RoomId"`, `"TaskId"`, `"AgentConfig"`, `"TargetUserId"`,
		`"Config"`, `"LLMConfig"`, `"Mode":"ArkV3"`} {
		if !strings.Contains(s, want) {
			t.Fatalf("marshaled request missing %s:\n%s", want, s)
		}
	}
}

func TestClientCallSuccess(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// The request must be signed and carry the action.
		if r.Header.Get("Authorization") == "" {
			t.Error("request not signed")
		}
		if got := r.Header.Get("User-Agent"); got != "vertc/1.2.3 invocation/skill skill/byted-interactai-guide#0.0.1" {
			t.Errorf("User-Agent = %q", got)
		}
		if r.URL.Query().Get("Action") != "StartVoiceChat" {
			t.Errorf("action = %q", r.URL.Query().Get("Action"))
		}
		body, _ := io.ReadAll(r.Body)
		if !strings.Contains(string(body), `"AppId":"app"`) {
			t.Errorf("body missing AppId: %s", body)
		}
		// StartVoiceChat's real Result is a bare "ok" string, not an object.
		_, _ = io.WriteString(w, `{"ResponseMetadata":{"RequestId":"rid"},"Result":"ok"}`)
	}))
	defer srv.Close()

	client := testClient(srv)
	client.OpenAPI.UserAgent = "vertc/1.2.3 invocation/skill skill/byted-interactai-guide#0.0.1"
	res, err := client.StartVoiceChat(context.Background(), sampleStartReq())
	if err != nil {
		t.Fatalf("StartVoiceChat: %v", err)
	}
	// TaskId is client-supplied and echoed back (server does not return it).
	if res.TaskID != "task" {
		t.Fatalf("TaskId = %q, want the client-supplied \"task\"", res.TaskID)
	}
}

func TestClientCallAPIError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(400)
		_, _ = io.WriteString(w, `{"ResponseMetadata":{"RequestId":"rid","Error":{"Code":"SignatureDoesNotMatch","Message":"bad sig"}}}`)
	}))
	defer srv.Close()

	_, err := testClient(srv).StartVoiceChat(context.Background(), sampleStartReq())
	ae, ok := err.(*APIError)
	if !ok {
		t.Fatalf("expected *APIError, got %T: %v", err, err)
	}
	if ae.Code != "SignatureDoesNotMatch" || ae.RequestID != "rid" {
		t.Fatalf("unexpected APIError: %+v", ae)
	}
}
